// Package workerpb defines the Worker RPC contract between the gateway
// supervisor (API process) and one per-session worker process.
//
// The contract deliberately carries only canonical runtime fields (see
// runtime/contract.go and runtime/events.go): model/session/caller/workspace
// identifiers, canonical messages, tools, and canonical events. There is NO
// OpenAI JSON and NO agent-specific field anywhere in this contract. nsjail is
// a worker-side startup detail and never appears here — the supervisor
// assembles the jail profile locally from config + workspace paths.
//
// Transport: one gRPC server per session, served by the worker process on a
// per-session Unix socket; the supervisor is the client. One worker process =
// one session = one AgentSession.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worker/proto/worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is "ok" on success.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// version identifies the worker implementation.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// pid is the worker process's own PID.
	Pid           int32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_worker_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FirstInput    *Input                 `protobuf:"bytes,6,opt,name=first_input,json=firstInput,proto3" json:"first_input,omitempty"`
	AgentConfig   *AgentExecutionConfig  `protobuf:"bytes,7,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	ProviderModel string                 `protobuf:"bytes,8,opt,name=provider_model,json=providerModel,proto3" json:"provider_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *StartSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *StartSessionRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StartSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StartSessionRequest) GetFirstInput() *Input {
	if x != nil {
		return x.FirstInput
	}
	return nil
}

func (x *StartSessionRequest) GetAgentConfig() *AgentExecutionConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *StartSessionRequest) GetProviderModel() string {
	if x != nil {
		return x.ProviderModel
	}
	return ""
}

type AgentExecutionConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	DefaultModel     string                 `protobuf:"bytes,2,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	Permission       string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	TurnTimeoutNanos int64                  `protobuf:"varint,4,opt,name=turn_timeout_nanos,json=turnTimeoutNanos,proto3" json:"turn_timeout_nanos,omitempty"`
	MaxConcurrency   int32                  `protobuf:"varint,5,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Env              map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentExecutionConfig) Reset() {
	*x = AgentExecutionConfig{}
	mi := &file_worker_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecutionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecutionConfig) ProtoMessage() {}

func (x *AgentExecutionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecutionConfig.ProtoReflect.Descriptor instead.
func (*AgentExecutionConfig) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *AgentExecutionConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentExecutionConfig) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *AgentExecutionConfig) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *AgentExecutionConfig) GetTurnTimeoutNanos() int64 {
	if x != nil {
		return x.TurnTimeoutNanos
	}
	return 0
}

func (x *AgentExecutionConfig) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *AgentExecutionConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type StartSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lifecycle_mode mirrors runtime.Descriptor.LifecycleMode
	// ("persistent_process"). The supervisor uses it to
	// decide whether an abort tears down the process or just cancels the turn.
	LifecycleMode string `protobuf:"bytes,1,opt,name=lifecycle_mode,json=lifecycleMode,proto3" json:"lifecycle_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_worker_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StartSessionResponse) GetLifecycleMode() string {
	if x != nil {
		return x.LifecycleMode
	}
	return ""
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         *Input                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_worker_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{6}
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *AbortSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionResponse) Reset() {
	*x = AbortSessionResponse{}
	mi := &file_worker_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionResponse) ProtoMessage() {}

func (x *AbortSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionResponse.ProtoReflect.Descriptor instead.
func (*AbortSessionResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{9}
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{10}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_worker_proto_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{11}
}

// Input is one canonical turn (runtime.Input).
type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_worker_proto_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{12}
}

func (x *Input) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Input) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Input) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message is one canonical conversation message (runtime.Message).
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system", "user", "assistant", or "tool"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // optional sender/function name
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,5,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // set on tool-result messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_worker_proto_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{13}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

// Tool describes a callable tool exposed to an agent (runtime.Tool).
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON Schema fragment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_worker_proto_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{14}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ToolCall is a tool invocation or its result (runtime.ToolCall).
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                   // set on tool-result frames
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"` // set on tool-result frames
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_worker_proto_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{15}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// PermissionRequest is a canonical permission request (runtime.PermissionRequest).
type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_worker_proto_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{16}
}

func (x *PermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Usage reports token accounting (runtime.Usage).
type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_worker_proto_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{17}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// EventFrame is one canonical runtime event (runtime.Event) serialized over
// the wire. type is the runtime.EventType string.
type EventFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text            string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Tool            *ToolCall              `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Permission      *PermissionRequest     `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	Usage           *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	FinishReason    string                 `protobuf:"bytes,7,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	NativeSessionId string                 `protobuf:"bytes,9,opt,name=native_session_id,json=nativeSessionId,proto3" json:"native_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_worker_proto_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_worker_proto_worker_proto_rawDescGZIP(), []int{18}
}

func (x *EventFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventFrame) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EventFrame) GetTool() *ToolCall {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *EventFrame) GetPermission() *PermissionRequest {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *EventFrame) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *EventFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EventFrame) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *EventFrame) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventFrame) GetNativeSessionId() string {
	if x != nil {
		return x.NativeSessionId
	}
	return ""
}

var File_worker_proto_worker_proto protoreflect.FileDescriptor

const file_worker_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x19worker/proto/worker.proto\x12\x0egateway.worker\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n" +
	"\rHealthRequest\"T\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"\xc3\x03\n" +
	"\x13StartSessionRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\tR\bcallerId\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12M\n" +
	"\bmetadata\x18\x05 \x03(\v21.gateway.worker.StartSessionRequest.MetadataEntryR\bmetadata\x126\n" +
	"\vfirst_input\x18\x06 \x01(\v2\x15.gateway.worker.InputR\n" +
	"firstInput\x12G\n" +
	"\fagent_config\x18\a \x01(\v2$.gateway.worker.AgentExecutionConfigR\vagentConfig\x12%\n" +
	"\x0eprovider_model\x18\b \x01(\tR\rproviderModel\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x14AgentExecutionConfig\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12#\n" +
	"\rdefault_model\x18\x02 \x01(\tR\fdefaultModel\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12,\n" +
	"\x12turn_timeout_nanos\x18\x04 \x01(\x03R\x10turnTimeoutNanos\x12'\n" +
	"\x0fmax_concurrency\x18\x05 \x01(\x05R\x0emaxConcurrency\x12?\n" +
	"\x03env\x18\x06 \x03(\v2-.gateway.worker.AgentExecutionConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x14StartSessionResponse\x12%\n" +
	"\x0elifecycle_mode\x18\x01 \x01(\tR\rlifecycleMode\"^\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x05input\x18\x02 \x01(\v2\x15.gateway.worker.InputR\x05input\"\x13\n" +
	"\x11SendInputResponse\"4\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13AbortSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14AbortSessionResponse\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"\xe6\x01\n" +
	"\x05Input\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.gateway.worker.MessageR\bmessages\x12*\n" +
	"\x05tools\x18\x02 \x03(\v2\x14.gateway.worker.ToolR\x05tools\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.gateway.worker.Input.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x127\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x18.gateway.worker.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x05 \x01(\tR\n" +
	"toolCallId\"u\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\x98\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"S\n" +
	"\x11PermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"r\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xd1\x02\n" +
	"\n" +
	"EventFrame\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12,\n" +
	"\x04tool\x18\x03 \x01(\v2\x18.gateway.worker.ToolCallR\x04tool\x12A\n" +
	"\n" +
	"permission\x18\x04 \x01(\v2!.gateway.worker.PermissionRequestR\n" +
	"permission\x12+\n" +
	"\x05usage\x18\x05 \x01(\v2\x15.gateway.worker.UsageR\x05usage\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12#\n" +
	"\rfinish_reason\x18\a \x01(\tR\ffinishReason\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12*\n" +
	"\x11native_session_id\x18\t \x01(\tR\x0fnativeSessionId2\x87\x04\n" +
	"\x06Worker\x12G\n" +
	"\x06Health\x12\x1d.gateway.worker.HealthRequest\x1a\x1e.gateway.worker.HealthResponse\x12Y\n" +
	"\fStartSession\x12#.gateway.worker.StartSessionRequest\x1a$.gateway.worker.StartSessionResponse\x12P\n" +
	"\tSendInput\x12 .gateway.worker.SendInputRequest\x1a!.gateway.worker.SendInputResponse\x12Q\n" +
	"\fStreamEvents\x12#.gateway.worker.StreamEventsRequest\x1a\x1a.gateway.worker.EventFrame0\x01\x12Y\n" +
	"\fAbortSession\x12#.gateway.worker.AbortSessionRequest\x1a$.gateway.worker.AbortSessionResponse\x12Y\n" +
	"\fCloseSession\x12#.gateway.worker.CloseSessionRequest\x1a$.gateway.worker.CloseSessionResponseB>Z<github.com/tianlinzz/agent-cli-gateway/worker/proto;workerpbb\x06proto3"

var (
	file_worker_proto_worker_proto_rawDescOnce sync.Once
	file_worker_proto_worker_proto_rawDescData []byte
)

func file_worker_proto_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_worker_proto_rawDesc), len(file_worker_proto_worker_proto_rawDesc)))
	})
	return file_worker_proto_worker_proto_rawDescData
}

var file_worker_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_worker_proto_worker_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: gateway.worker.HealthRequest
	(*HealthResponse)(nil),       // 1: gateway.worker.HealthResponse
	(*StartSessionRequest)(nil),  // 2: gateway.worker.StartSessionRequest
	(*AgentExecutionConfig)(nil), // 3: gateway.worker.AgentExecutionConfig
	(*StartSessionResponse)(nil), // 4: gateway.worker.StartSessionResponse
	(*SendInputRequest)(nil),     // 5: gateway.worker.SendInputRequest
	(*SendInputResponse)(nil),    // 6: gateway.worker.SendInputResponse
	(*StreamEventsRequest)(nil),  // 7: gateway.worker.StreamEventsRequest
	(*AbortSessionRequest)(nil),  // 8: gateway.worker.AbortSessionRequest
	(*AbortSessionResponse)(nil), // 9: gateway.worker.AbortSessionResponse
	(*CloseSessionRequest)(nil),  // 10: gateway.worker.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 11: gateway.worker.CloseSessionResponse
	(*Input)(nil),                // 12: gateway.worker.Input
	(*Message)(nil),              // 13: gateway.worker.Message
	(*Tool)(nil),                 // 14: gateway.worker.Tool
	(*ToolCall)(nil),             // 15: gateway.worker.ToolCall
	(*PermissionRequest)(nil),    // 16: gateway.worker.PermissionRequest
	(*Usage)(nil),                // 17: gateway.worker.Usage
	(*EventFrame)(nil),           // 18: gateway.worker.EventFrame
	nil,                          // 19: gateway.worker.StartSessionRequest.MetadataEntry
	nil,                          // 20: gateway.worker.AgentExecutionConfig.EnvEntry
	nil,                          // 21: gateway.worker.Input.MetadataEntry
	(*structpb.Struct)(nil),      // 22: google.protobuf.Struct
}
var file_worker_proto_worker_proto_depIdxs = []int32{
	19, // 0: gateway.worker.StartSessionRequest.metadata:type_name -> gateway.worker.StartSessionRequest.MetadataEntry
	12, // 1: gateway.worker.StartSessionRequest.first_input:type_name -> gateway.worker.Input
	3,  // 2: gateway.worker.StartSessionRequest.agent_config:type_name -> gateway.worker.AgentExecutionConfig
	20, // 3: gateway.worker.AgentExecutionConfig.env:type_name -> gateway.worker.AgentExecutionConfig.EnvEntry
	12, // 4: gateway.worker.SendInputRequest.input:type_name -> gateway.worker.Input
	13, // 5: gateway.worker.Input.messages:type_name -> gateway.worker.Message
	14, // 6: gateway.worker.Input.tools:type_name -> gateway.worker.Tool
	21, // 7: gateway.worker.Input.metadata:type_name -> gateway.worker.Input.MetadataEntry
	15, // 8: gateway.worker.Message.tool_calls:type_name -> gateway.worker.ToolCall
	22, // 9: gateway.worker.Tool.parameters:type_name -> google.protobuf.Struct
	22, // 10: gateway.worker.ToolCall.arguments:type_name -> google.protobuf.Struct
	15, // 11: gateway.worker.EventFrame.tool:type_name -> gateway.worker.ToolCall
	16, // 12: gateway.worker.EventFrame.permission:type_name -> gateway.worker.PermissionRequest
	17, // 13: gateway.worker.EventFrame.usage:type_name -> gateway.worker.Usage
	0,  // 14: gateway.worker.Worker.Health:input_type -> gateway.worker.HealthRequest
	2,  // 15: gateway.worker.Worker.StartSession:input_type -> gateway.worker.StartSessionRequest
	5,  // 16: gateway.worker.Worker.SendInput:input_type -> gateway.worker.SendInputRequest
	7,  // 17: gateway.worker.Worker.StreamEvents:input_type -> gateway.worker.StreamEventsRequest
	8,  // 18: gateway.worker.Worker.AbortSession:input_type -> gateway.worker.AbortSessionRequest
	10, // 19: gateway.worker.Worker.CloseSession:input_type -> gateway.worker.CloseSessionRequest
	1,  // 20: gateway.worker.Worker.Health:output_type -> gateway.worker.HealthResponse
	4,  // 21: gateway.worker.Worker.StartSession:output_type -> gateway.worker.StartSessionResponse
	6,  // 22: gateway.worker.Worker.SendInput:output_type -> gateway.worker.SendInputResponse
	18, // 23: gateway.worker.Worker.StreamEvents:output_type -> gateway.worker.EventFrame
	9,  // 24: gateway.worker.Worker.AbortSession:output_type -> gateway.worker.AbortSessionResponse
	11, // 25: gateway.worker.Worker.CloseSession:output_type -> gateway.worker.CloseSessionResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_worker_proto_worker_proto_init() }
func file_worker_proto_worker_proto_init() {
	if File_worker_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_worker_proto_rawDesc), len(file_worker_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_worker_proto_msgTypes,
	}.Build()
	File_worker_proto_worker_proto = out.File
	file_worker_proto_worker_proto_goTypes = nil
	file_worker_proto_worker_proto_depIdxs = nil
}
